development:
  adapter: postgresql
  encoding: unicode
  database: nitrous-etsy
  pool: 5
  host: localhost
  username: nitrous
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: nitrous-etsy
  pool: 5
  host: localhost
  username: nitrous
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: djg-etsy
  pool: 5
  